name: Azure Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy apps to Azure

    runs-on: ubuntu-latest

    steps:
    - name: Deploy MD2HTML
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        gh workflow run "Azure Deployment" --repo hackersground-kr/markdown-to-html
